import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "@/components/provider";
import { HelpCircleIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "Music generator",
  description: "Generated by Cku24",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
          <main className="flex h-screen items-center justify-center overflow-y-auto">
            <div className="flex-1 items-center justify-center">{children}</div>
            <div className="w-full flex-1 items-center">
              <div className="flex justify-center">
                <HelpCircleIcon />
              </div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
